image:
  - Visual Studio 2017
clone_depth: 10
configuration: Release
platform: AnyCPU
install:
  - git clone -q --depth=1 --branch=master https://github.com/markfinal/bam-compress.git ../bam-compress
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.zip?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - 7z x bam.zip -oc:\BuildAMation
test_script:
  - c:\BuildAMation\bam_publish\env.bat
  - cmd: "SET PATH=C:\\Python27-x64;%PATH%"
  - python c:\BuildAMation\bam_publish\tests\runtests.py -c debug -c profile -j 0 --VisualC.version=15.0 -x Mingw --nodefaultrepo -r .
