clone_depth: 10
configuration: Release
platform: AnyCPU
install:
  - git clone -q --depth=1 --branch=master https://github.com/markfinal/bam-compress.git ../bam-compress
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/ubuntu_install_scripts.tar?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - cmd: 7z x bam.tar -oc:\BuildAMation
  - sh: mkdir ~/BuildAMation
  - sh: tar xf bam.tar -C ~/BuildAMation
  - sh: tar xf ubuntu_install_scripts.tar ~/CI
  - sh: ls ~/CI
environment:
  matrix:
  - job_name: Ubuntu 18 (GCC 9) Native
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 9) MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 8) Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 8) MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 7) Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 7) MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 6) Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 18 (GCC 6) MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  #- job_name: Ubuntu 16 (GCC 5) Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
  #- job_name: Ubuntu 16 (GCC 5) MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
  #- job_name: Visual Studio 2019 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  #- job_name: Visual Studio 2019 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  #- job_name: Visual Studio 2019 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
  #- job_name: Visual Studio 2017 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #- job_name: Visual Studio 2017 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #- job_name: Visual Studio 2017 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  #- job_name: Visual Studio 2015 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2015 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2015 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2013 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2013 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2013 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2012 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2012 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2012 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2010 Native
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2010 MakeFile
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #- job_name: Visual Studio 2010 VSSolution
  #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
for:
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 9) Native
    environment:
      BAM_BUILD_MODE: Native
      GCC_VERSION: 9
    before_test:
      - sh: ~/CI/ubuntu_install_scripts/gcc9.sh
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 9) MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile
      GCC_VERSION: 9
    before_test:
      - sh: sudo apt-get -q -y --no-install-recommends install g++-9 g++-9-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 5  --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-9 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-9 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-9 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 8) Native
    environment:
      BAM_BUILD_MODE: Native
      GCC_VERSION: 8
    before_test:
      - sh: sudo apt-get -q -y --no-install-recommends install g++-8 g++-8-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 8) MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile
      GCC_VERSION: 8
    before_test:
      - sh: sudo apt-get -q -y --no-install-recommends install g++-8 g++-8-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 7) Native
    environment:
      BAM_BUILD_MODE: Native
      GCC_VERSION: 7
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-7 g++-7-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 7) MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile
      GCC_VERSION: 7
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-7 g++-7-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 6) Native
    environment:
      BAM_BUILD_MODE: Native
      GCC_VERSION: 6
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-6 g++-6-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 5  --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-6 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-6 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-6 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-6 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-6
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 6) MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile
      GCC_VERSION: 6
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-6 g++-6-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 5  --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-6 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-6 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-6 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-6 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-6
  - matrix:
      only:
        - job_name: Ubuntu 16 (GCC 5) Native
    environment:
      BAM_BUILD_MODE: Native
      GCC_VERSION: 5
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++ g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-5 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-5 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-5 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-5 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-5
  - matrix:
      only:
        - job_name: Ubuntu 16 (GCC 5) MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile
      GCC_VERSION: 5
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++ g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-5 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-5 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-5 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-5 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-5
  - matrix:
      only:
        - job_name: Visual Studio 2019 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 16
  - matrix:
      only:
        - job_name: Visual Studio 2019 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 16
  - matrix:
      only:
        - job_name: Visual Studio 2019 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 16
  - matrix:
      only:
        - job_name: Visual Studio 2017 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 15.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2017 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 15.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2017 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 15.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2015 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 14.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2015 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 14.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2015 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 14.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2013 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 12.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2013 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 12.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2013 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 12.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2012 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 11.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2012 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 11.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2012 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 11.0
      EXTRA_TEST_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2010 Native
    environment:
      BAM_BUILD_MODE: Native
      VC_VERSION: 10.0
      EXTRA_TEST_ARGS: --C.bitdepth=32
  - matrix:
      only:
        - job_name: Visual Studio 2010 MakeFile
    environment:
      BAM_BUILD_MODE: MakeFile --MakeFile.format=NMAKE
      VC_VERSION: 10.0
      EXTRA_TEST_ARGS: --C.bitdepth=32
  - matrix:
      only:
        - job_name: Visual Studio 2010 VSSolution
    environment:
      BAM_BUILD_MODE: VSSolution
      VC_VERSION: 10.0
      EXTRA_TEST_ARGS: --C.bitdepth=32
build: off
test_script:
  - cmd: c:\BuildAMation\env.bat
  - cmd: "SET PATH=C:\\Python27-x64;%PATH%"
  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% -b %BAM_BUILD_MODE% -c debug -c profile -j0 -d --nodefaultrepo -r . %EXTRA_TEST_ARGS%
  - sh: source ~/BuildAMation/env.sh
  - sh: python ~/BuildAMation/tests/runtests.py --Gcc.version=$GCC_VERSION -b $BAM_BUILD_MODE -c debug -c profile -j0 -d --nodefaultrepo -r . $EXTRA_TEST_ARGS
