image:
  - Visual Studio 2017
  - Ubuntu1804
clone_depth: 10
configuration: Release
platform: AnyCPU
for:
  - matrix:
      only:
        - image: Ubuntu1804
    environment:
      GCC_VERSION: 7
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
        VC_VERSION: 15.0
        VC_PRERELEASE_ARGS:
install:
  - git clone -q --depth=1 --branch=master https://github.com/markfinal/bam-compress.git ../bam-compress
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - cmd: 7z x bam.tar -oc:\BuildAMation
  - sh: tar xf bam.tar -C ~/BuildAMation
build: off
test_script:
  - cmd: c:\BuildAMation\bam_publish\env.bat
  - cmd: "SET PATH=C:\\Python27-x64;%PATH%"
  - cmd: python c:\BuildAMation\bam_publish\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
  - cmd: python c:\BuildAMation\bam_publish\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b VSSolution -c debug -c profile -j0 -d --nodefaultrepo -r .
  - cmd: python c:\BuildAMation\bam_publish\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b MakeFile -c debug -c profile -j0 -d --MakeFile.format=NMAKE --nodefaultrepo -r .
  - sh: source ~/BuildAMation/bam_publish/env.sh
  - sh: python ~/BuildAMation/bam_publish/tests/runtests.py --Gcc.version=$GCC_VERSION -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
  - sh: python ~/BuildAMation/bam_publish/tests/runtests.py --Gcc.version=$GCC_VERSION -b MakeFile -c debug -c profile -j0 -d --nodefaultrepo -r .
