clone_depth: 10
configuration: Release
platform: AnyCPU
install:
  - sh: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sh: sudo apt-get -q update
  - sh: sudo update-alternatives --remove-all gcc
  - git clone -q --depth=1 --branch=master https://github.com/markfinal/bam-compress.git ../bam-compress
  - ps: Start-FileDownload 'https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.tar?branch=master&job=Image%3A%20Visual%20Studio%202017'
  - cmd: 7z x bam.tar -oc:\BuildAMation
  - sh: mkdir ~/BuildAMation
  - sh: tar xf bam.tar -C ~/BuildAMation
environment:
  matrix:
  - job_name: Ubuntu 18 (GCC 9)
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  - job_name: Ubuntu 18 (GCC 8)
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  - job_name: Ubuntu 18 (GCC 7)
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  - job_name: Ubuntu 18 (GCC 6)
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
  - job_name: Ubuntu 16 (GCC 5)
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1604
  - job_name: Visual Studio 2019 Preview
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
  - job_name: Visual Studio 2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - job_name: Visual Studio 2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - job_name: Visual Studio 2013
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - job_name: Visual Studio 2012
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - job_name: Visual Studio 2010
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
for:
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 9)
    environment:
      GCC_VERSION: 9
    before_test:
      - sh: sudo apt-get -q -y --no-install-recommends install g++-9 g++-9-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 5  --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-9 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-9 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-9 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 8)
    environment:
      GCC_VERSION: 8
    before_test:
      - sh: sudo apt-get -q -y --no-install-recommends install g++-8 g++-8-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 7)
    environment:
      GCC_VERSION: 7
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-7 g++-7-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 5  --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-8 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-8 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-8 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-8 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-8
  - matrix:
      only:
        - job_name: Ubuntu 18 (GCC 6)
    environment:
      GCC_VERSION: 6
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++-6 g++-6-multilib g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-7 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-7 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-7 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-7 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-7
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 5  --slave /usr/bin/g++ g++ /usr/bin/g++-6 --slave /usr/bin/gcov gcov /usr/bin/gcov-6 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-6 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-6 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-6 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-6 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-6
  - matrix:
      only:
        - job_name: Ubuntu 16 (GCC 5)
    environment:
      GCC_VERSION: 5
    before_test:
      - sh: sudo apt-get -q update
      - sh: sudo apt-get -q -y --no-install-recommends install g++ g++-multilib
      - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10 --slave /usr/bin/g++ g++ /usr/bin/g++-5 --slave /usr/bin/gcov gcov /usr/bin/gcov-5 --slave /usr/bin/gcov-dump gcov-dump /usr/bin/gcov-dump-5 --slave /usr/bin/gcov-tool gcov-tool /usr/bin/gcov-tool-5 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-5 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-5 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-5
  - matrix:
      only:
        - job_name: Visual Studio 2019 Preview
    environment:
        VC_VERSION: 16
        VC_PRERELEASE_ARGS: "--VisualC.discoverprereleases"
  - matrix:
      only:
        - job_name: Visual Studio 2017
    environment:
        VC_VERSION: 15.0
        VC_PRERELEASE_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2015
    environment:
        VC_VERSION: 14.0
        VC_PRERELEASE_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2013
    environment:
        VC_VERSION: 12.0
        VC_PRERELEASE_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2012
    environment:
        VC_VERSION: 11.0
        VC_PRERELEASE_ARGS:
  - matrix:
      only:
        - job_name: Visual Studio 2010
    environment:
        VC_VERSION: 10.0
        VC_PRERELEASE_ARGS:
build: off
test_script:
  - cmd: c:\BuildAMation\env.bat
  - cmd: "SET PATH=C:\\Python27-x64;%PATH%"
  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b VSSolution -c debug -c profile -j0 -d --nodefaultrepo -r .
  - cmd: python c:\BuildAMation\tests\runtests.py -x Mingw --VisualC.version=%VC_VERSION% %VC_PRERELEASE_ARGS% -b MakeFile -c debug -c profile -j0 -d --MakeFile.format=NMAKE --nodefaultrepo -r .
  - sh: source ~/BuildAMation/env.sh
  - sh: sudo update-alternatives --set gcc /usr/bin/gcc-$GCC_VERSION
  - sh: python ~/BuildAMation/tests/runtests.py --Gcc.version=$GCC_VERSION -b Native -c debug -c profile -j0 -d --nodefaultrepo -r .
  - sh: python ~/BuildAMation/tests/runtests.py --Gcc.version=$GCC_VERSION -b MakeFile -c debug -c profile -j0 -d --nodefaultrepo -r .
