image:
  - Visual Studio 2017
clone_depth: 10
configuration: Release
platform: AnyCPU
install:
  - appveyor DownloadFile "https://ci.appveyor.com/api/projects/markfinal/buildamation/artifacts/bam.zip?branch=master&job=Visual%20Studio%202017" -FileName bam.zip
  - dir
  - 7z x bam.zip -oc:\BuildAMation
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
